### ISSUE TITLE
Firefox Cross-Origin compatibility

### ISSUE THREAD

**Issue by kggp1995** [dharmaprotocol/relayer-kit#21]
As discussed with @chrismin at ETHIndia, we have issues viewing the dashboard on firefox browsers.
Working with Chrome as usual.

**Comment by kggp1995** [comment]
Hey guys, this works fine on firefox too. Has to do with the environment variables for remote nodes!

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/11145839/43990476-bf38c1c2-9d79-11e8-886e-9b14c28e40b3.png">

**Comment by JFrankfurt** [comment]
@kggp1995 I ran into this as well. How did you fix it?

**Comment by kggp1995** [comment]
@JFrankfurt , Are you running this on a localhost?

**Comment by kggp1995** [comment]
I edit `.env.development` under `relayer-starter-kit`
