### ISSUE TITLE
Need for collateralization of ERC-721 NFTs

### ISSUE THREAD

**Issue by kggp1995** [dharmaprotocol/relayer-kit#22]
This is an issue following up a conversation with @nadavhollander  & @chrismin  at ETHIndia.

We need to have a library contract for supporting collateralization of ERC-721 assets to counterpart units of trade/load such as ETH, DAI, etc.

I shall post more on this post the Hackathon event!

**Comment by nadavhollander** [comment]
@graemecode -- @kggp1995 and his partner in the ETHIndia hackathon are two developers who are deeply versed in Ethereum / eWASM / Solidity, and they had expressed interested in helping us get the ERC721 collateralizer up and running through open-source contributions.

@kggp1995 -- @graemecode is the engineer who is currently leading our efforts in building this component out.  I'll let him take it from here.

**Comment by nadavhollander** [comment]
Also -- two more things:

1. @kggp1995 could you invite your partner to this thread?
2. this conversation would probably be more fitting in the [Charta](https://github.com/dharmaprotocol/charta) repo

**Comment by kggp1995** [comment]
Thanks for the sync-up @nadavhollander ! It was nice meeting you all.

Yes, we will open a fresh issue under Charta repo & target issue on enhancing the collateralization.

Thanks to @chrismin who showed us a good start @ https://github.com/dharmaprotocol/charta/tree/master/contracts/
